import { createHash } from 'crypto';

import TuyaSharingAPI, { sharingCrypto } from '../src/core/TuyaSharingAPI';
import { TuyaSharingCredentials } from '../src/core/TuyaSharingAuth';

const VECTOR = {
  requestId: '11111111-2222-4333-8444-555555555555',
  refreshToken: 'refresh-token-example',
  hashKey: '2f8e45d2718f6379a7d756ee4efbd2d8',
  secret: '1dd590e96f369174',
  nonce: 'AbCdEfGh2345',
  raw: '{"homeId":"12345","enabled":true}',
  encrypted: 'QWJDZEVmR2gyMzQ1fE0r4LwkIokWNXt76o+e7Ol8tq4goqmK2FQdNmZRvmoe5eci1JyOCcyPyNafvAvneg==',
  sign: 'e3f3d16b7b3d90a4fb379197b163b320f10393c3a983293e9dfd35d5fd61415a',
  responseRaw: '{"devices":[{"id":"abc","online":true}]}',
  responseEncrypted: 'UXdFclR5VWk2Nzg5P3jF296qM4FoFmj2WynYiAcIt1Ls73r7Jm1uAGEH98uC+5hNj/yNsfJEj/HQXkgSIwpMoqDAtTA=',
};

function credentials(overrides: Partial<TuyaSharingCredentials['token_info']> = {}): TuyaSharingCredentials {
  return {
    client_id: 'client-example',
    user_code: 'user-code',
    app_schema: 'tuyaSmart',
    terminal_id: 'terminal-example',
    endpoint: 'https://openapi.example.test',
    token_info: {
      t: 1_785_067_200_000,
      uid: 'user-example',
      expire_time: 7200,
      access_token: 'access-token-example',
      refresh_token: VECTOR.refreshToken,
      ...overrides,
    },
  };
}

function jsonResponse(body: unknown): Response {
  return new Response(JSON.stringify(body), {
    status: 200,
    headers: { 'content-type': 'application/json' },
  });
}

describe('Tuya account-sharing crypto', () => {
  test('matches vectors generated by Tuya\'s official Python sharing SDK', () => {
    const hashKey = createHash('md5').update(VECTOR.requestId + VECTOR.refreshToken).digest('hex');
    expect(hashKey).toBe(VECTOR.hashKey);

    const secret = sharingCrypto.generateSecret(VECTOR.requestId, hashKey);
    expect(secret).toBe(VECTOR.secret);
    expect(sharingCrypto.encryptRequestPayload(VECTOR.raw, secret, VECTOR.nonce)).toBe(VECTOR.encrypted);
    expect(sharingCrypto.decryptResponsePayload(VECTOR.responseEncrypted, secret)).toBe(VECTOR.responseRaw);
    expect(sharingCrypto.signRequest(hashKey, {
      'X-appKey': 'client-example',
      'X-requestId': VECTOR.requestId,
      'X-sid': '',
      'X-time': '1785067200123',
      'X-token': 'access-token-example',
    }, VECTOR.encrypted, '')).toBe(VECTOR.sign);
  });

  test('encrypts, signs, sends, and decrypts a complete request', async () => {
    const fetchMock = jest.fn().mockResolvedValue(jsonResponse({
      success: true,
      result: VECTOR.responseEncrypted,
    }));
    const api = new TuyaSharingAPI({
      credentials: credentials(),
      fetch: fetchMock,
      now: () => 1_785_067_200_123,
      requestId: () => VECTOR.requestId,
      nonce: () => VECTOR.nonce,
    });

    await expect(api.get('/v1.0/test', { homeId: '12345', enabled: true })).resolves.toMatchObject({
      success: true,
      result: { devices: [{ id: 'abc', online: true }] },
    });

    const [rawUrl, init] = fetchMock.mock.calls[0] as [string, RequestInit];
    const url = new URL(rawUrl);
    expect(url.origin + url.pathname).toBe('https://openapi.example.test/v1.0/test');
    expect(url.searchParams.get('encdata')).toBe(VECTOR.encrypted);
    expect(init.method).toBe('GET');
    expect(init.body).toBeUndefined();
    expect(init.headers).toMatchObject({
      'X-appKey': 'client-example',
      'X-requestId': VECTOR.requestId,
      'X-time': '1785067200123',
      'X-token': 'access-token-example',
      'X-sign': VECTOR.sign,
    });
  });

  test('shares one refresh operation between concurrent requests and persists the result', async () => {
    const now = 1_785_067_200_123;
    const onTokenUpdate = jest.fn();
    const fetchMock = jest.fn().mockImplementation(async (rawUrl: string) => {
      if (rawUrl.includes('/v1.0/m/token/')) {
        return jsonResponse({
          success: true,
          t: now,
          result: {
            uid: 'refreshed-user',
            expireTime: 7200,
            accessToken: 'refreshed-access',
            refreshToken: 'refreshed-refresh',
          },
        });
      }
      return jsonResponse({ success: true, result: { ok: true } });
    });
    let requestNumber = 0;
    const api = new TuyaSharingAPI({
      credentials: credentials({ t: 0, expire_time: 1 }),
      fetch: fetchMock,
      now: () => now,
      requestId: () => `request-${++requestNumber}`,
      onTokenUpdate,
    });

    await Promise.all([api.get('/first'), api.get('/second')]);

    expect(fetchMock.mock.calls.filter(([url]) => String(url).includes('/v1.0/m/token/'))).toHaveLength(1);
    expect(onTokenUpdate).toHaveBeenCalledTimes(1);
    expect(api.getPersistedToken()).toEqual({
      t: now,
      uid: 'refreshed-user',
      expire_time: 7200,
      access_token: 'refreshed-access',
      refresh_token: 'refreshed-refresh',
    });
  });
});
